/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Dark_Targets.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import gsap from "gsap";
import { useNavigate } from "react-router-dom";
import { useToggleRoomStore } from "../../../stores/toggleRoomStore";
import { useFloatingCardStore } from "../../../stores/floatingCardStore";

export default function Model(props) {
  let navigate = useNavigate();
  const { nodes } = useGLTF("/models/Dark Room/Dark_Targets.glb");
  const setFloatingCard = useFloatingCardStore(
    (state) => state.setFloatingCard
  );

  const whiteMaterial = new THREE.MeshBasicMaterial({ color: 0xffffff });

  const aboutAnimRef = useRef();
  const devWorkAnimRef = useRef();

  const animationPairs = {
    About_Hitbox: { ref: aboutAnimRef },
    Dev_Work_Hitbox: { ref: devWorkAnimRef },
  };

  const { isDarkRoom, setDarkRoom, isTransitioning } = useToggleRoomStore();
  //Handle Hover
  const onHover = (key, isHovering, event) => {
    const animObject = animationPairs[key];
    gsap.to(animObject.ref.current.scale, {
      x: isHovering ? 1 : 0,
      y: isHovering ? 1 : 0,
      z: isHovering ? 1 : 0,
      duration: 0.5,
    });

    if (key === "About_Hitbox") {
      if (isHovering && event) {
        setFloatingCard(true, [event.clientX, event.clientY - 40], "About Us");
      } else {
        setFloatingCard(false, [0, 0], "");
      }
    } else if (key === "Dev_Work_Hitbox") {
      if (isHovering && event) {
        setFloatingCard(
          true,
          [event.clientX, event.clientY - 40],
          "Our Projects"
        );
      } else {
        setFloatingCard(false, [0, 0], "");
      }
    }
  };

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.About_Hitbox.geometry}
        material={nodes.About_Hitbox.material}
        visible={false}
        position={[0.679, 1.571 - 0.02, -1.368]}
        onPointerOver={(e) => {
          onHover("About_Hitbox", true, e);
          document.body.style.cursor = "pointer";
        }}
        onPointerOut={(e) => {
          onHover("About_Hitbox", false, e);
          document.body.style.cursor = "auto";
        }}
        onClick={() => {
          navigate("/about");
        }}
      />
      <mesh
        ref={aboutAnimRef}
        geometry={nodes.About_Hitbox_Anim.geometry}
        material={whiteMaterial}
        scale={[0, 0, 0]}
        position={[0.679, 1.571 - 0.02, -1.368]}
      />
      <mesh
        geometry={nodes.Dev_Work_Hitbox.geometry}
        material={nodes.Dev_Work_Hitbox.material}
        visible={false}
        position={[-0.457, 0.597 - 0.02, 1.021]}
        onPointerOver={(e) => {
          onHover("Dev_Work_Hitbox", true, e);
          document.body.style.cursor = "pointer";
        }}
        onPointerOut={(e) => {
          onHover("Dev_Work_Hitbox", false, e);
          document.body.style.cursor = "auto";
        }}
        onClick={(e) => {
          if (e.shiftKey) {
            if (!isTransitioning) {
              setDarkRoom(!isDarkRoom);
            }
          } else {
            navigate("/dev-work");
          }
        }}
      />
      <mesh
        ref={devWorkAnimRef}
        geometry={nodes.Dev_Work_Hitbox_Anim.geometry}
        material={whiteMaterial}
        scale={[0, 0, 0]}
        position={[-1.298, 1.166, 1.75]}
      />
    </group>
  );
}

useGLTF.preload("/models/Dark Room/Dark_Targets.glb");
